ALTER TABLE IF EXISTS cron_runs
  ADD COLUMN IF NOT EXISTS symbols_scanned INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS candidates_found INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ai_validations INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ai_confirmations INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ai_rejections INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ai_failures INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS stop_losses_triggered INTEGER DEFAULT 0;

ALTER TABLE IF EXISTS alerts
  ADD COLUMN IF NOT EXISTS ai_validated BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS ai_confidence VARCHAR(10),
  ADD COLUMN IF NOT EXISTS ai_reasoning TEXT,
  ADD COLUMN IF NOT EXISTS ai_adjusted_stop DECIMAL(20,8),
  ADD COLUMN IF NOT EXISTS ai_adjusted_target DECIMAL(20,8),
  ADD COLUMN IF NOT EXISTS ai_model VARCHAR(50),
  ADD COLUMN IF NOT EXISTS cron_run_id INTEGER REFERENCES cron_runs(id);

CREATE TABLE IF NOT EXISTS agent_cooldowns (
  symbol VARCHAR(20) NOT NULL,
  direction VARCHAR(10) NOT NULL CHECK(direction IN ('bull', 'bear')),
  last_alert_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  rejection_count INTEGER DEFAULT 0,
  cooldown_until TIMESTAMPTZ,
  PRIMARY KEY (symbol, direction)
);

CREATE TABLE IF NOT EXISTS daily_alert_counts (
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  alert_date DATE NOT NULL DEFAULT CURRENT_DATE,
  count INTEGER DEFAULT 0,
  PRIMARY KEY (user_id, alert_date)
);
