INSERT INTO universe_symbols (symbol, name, asset_type, sector, tags, is_active)
VALUES
  ('AAPL', 'Apple Inc', 'equity', 'technology', '["mega_liquid"]'::jsonb, TRUE),
  ('MSFT', 'Microsoft Corp', 'equity', 'technology', '["mega_liquid"]'::jsonb, TRUE),
  ('AMZN', 'Amazon.com Inc', 'equity', 'consumer_discretionary', '["mega_liquid"]'::jsonb, TRUE),
  ('GOOGL', 'Alphabet Class A', 'equity', 'communication_services', '["mega_liquid"]'::jsonb, TRUE),
  ('META', 'Meta Platforms', 'equity', 'communication_services', '["mega_liquid"]'::jsonb, TRUE),
  ('NVDA', 'NVIDIA Corp', 'equity', 'technology', '["mega_liquid","ai"]'::jsonb, TRUE),
  ('TSLA', 'Tesla Inc', 'equity', 'consumer_discretionary', '["mega_liquid","ev"]'::jsonb, TRUE),
  ('BRK.B', 'Berkshire Hathaway B', 'equity', 'financials', '["mega_liquid"]'::jsonb, TRUE),
  ('JPM', 'JPMorgan Chase', 'equity', 'financials', '["mega_liquid"]'::jsonb, TRUE),
  ('JNJ', 'Johnson and Johnson', 'equity', 'healthcare', '["mega_liquid"]'::jsonb, TRUE),
  ('V', 'Visa Inc', 'equity', 'financials', '["mega_liquid"]'::jsonb, TRUE),
  ('UNH', 'UnitedHealth Group', 'equity', 'healthcare', '["mega_liquid"]'::jsonb, TRUE),
  ('XOM', 'Exxon Mobil', 'equity', 'energy', '["mega_liquid"]'::jsonb, TRUE),
  ('PG', 'Procter and Gamble', 'equity', 'consumer_staples', '["mega_liquid"]'::jsonb, TRUE),
  ('MA', 'Mastercard Inc', 'equity', 'financials', '["mega_liquid"]'::jsonb, TRUE),
  ('HD', 'Home Depot', 'equity', 'consumer_discretionary', '["mega_liquid"]'::jsonb, TRUE),
  ('ABBV', 'AbbVie Inc', 'equity', 'healthcare', '["mega_liquid"]'::jsonb, TRUE),
  ('MRK', 'Merck and Co', 'equity', 'healthcare', '["mega_liquid"]'::jsonb, TRUE),
  ('AVGO', 'Broadcom Inc', 'equity', 'technology', '["mega_liquid"]'::jsonb, TRUE),
  ('COST', 'Costco Wholesale', 'equity', 'consumer_staples', '["mega_liquid"]'::jsonb, TRUE),
  ('PEP', 'PepsiCo', 'equity', 'consumer_staples', '["mega_liquid"]'::jsonb, TRUE),
  ('KO', 'Coca Cola', 'equity', 'consumer_staples', '["mega_liquid"]'::jsonb, TRUE),
  ('BAC', 'Bank of America', 'equity', 'financials', '["mega_liquid"]'::jsonb, TRUE),
  ('CVX', 'Chevron Corp', 'equity', 'energy', '["mega_liquid"]'::jsonb, TRUE),
  ('WMT', 'Walmart Inc', 'equity', 'consumer_staples', '["mega_liquid"]'::jsonb, TRUE),
  ('TMO', 'Thermo Fisher', 'equity', 'healthcare', '["mega_liquid"]'::jsonb, TRUE),
  ('CSCO', 'Cisco Systems', 'equity', 'technology', '["mega_liquid"]'::jsonb, TRUE),
  ('ACN', 'Accenture', 'equity', 'technology', '["mega_liquid"]'::jsonb, TRUE),
  ('CRM', 'Salesforce', 'equity', 'technology', '["mega_liquid"]'::jsonb, TRUE),
  ('ABT', 'Abbott Labs', 'equity', 'healthcare', '["mega_liquid"]'::jsonb, TRUE),
  ('MCD', 'McDonalds', 'equity', 'consumer_discretionary', '["mega_liquid"]'::jsonb, TRUE),
  ('DHR', 'Danaher Corp', 'equity', 'healthcare', '["mega_liquid"]'::jsonb, TRUE),
  ('ADBE', 'Adobe Inc', 'equity', 'technology', '["mega_liquid"]'::jsonb, TRUE),
  ('LIN', 'Linde plc', 'equity', 'materials', '["mega_liquid"]'::jsonb, TRUE),
  ('CMCSA', 'Comcast Corp', 'equity', 'communication_services', '["mega_liquid"]'::jsonb, TRUE),
  ('NFLX', 'Netflix Inc', 'equity', 'communication_services', '["mega_liquid"]'::jsonb, TRUE),
  ('AMD', 'Advanced Micro Devices', 'equity', 'technology', '["mega_liquid"]'::jsonb, TRUE),
  ('PFE', 'Pfizer Inc', 'equity', 'healthcare', '["mega_liquid"]'::jsonb, TRUE),
  ('DIS', 'Walt Disney', 'equity', 'communication_services', '["mega_liquid"]'::jsonb, TRUE),
  ('TXN', 'Texas Instruments', 'equity', 'technology', '["mega_liquid"]'::jsonb, TRUE),
  ('VZ', 'Verizon', 'equity', 'communication_services', '["mega_liquid"]'::jsonb, TRUE),
  ('NKE', 'Nike Inc', 'equity', 'consumer_discretionary', '["mega_liquid"]'::jsonb, TRUE),
  ('INTC', 'Intel Corp', 'equity', 'technology', '["mega_liquid"]'::jsonb, TRUE),
  ('ORCL', 'Oracle Corp', 'equity', 'technology', '["mega_liquid"]'::jsonb, TRUE),
  ('PM', 'Philip Morris', 'equity', 'consumer_staples', '["mega_liquid"]'::jsonb, TRUE),
  ('QCOM', 'Qualcomm', 'equity', 'technology', '["mega_liquid"]'::jsonb, TRUE),
  ('UPS', 'United Parcel Service', 'equity', 'industrials', '["mega_liquid"]'::jsonb, TRUE),
  ('HON', 'Honeywell', 'equity', 'industrials', '["mega_liquid"]'::jsonb, TRUE),
  ('LOW', 'Lowes', 'equity', 'consumer_discretionary', '["mega_liquid"]'::jsonb, TRUE),
  ('UNP', 'Union Pacific', 'equity', 'industrials', '["mega_liquid"]'::jsonb, TRUE),
  ('SPGI', 'S and P Global', 'equity', 'financials', '["mega_liquid"]'::jsonb, TRUE),
  ('CAT', 'Caterpillar', 'equity', 'industrials', '["mega_liquid"]'::jsonb, TRUE),
  ('GS', 'Goldman Sachs', 'equity', 'financials', '["mega_liquid"]'::jsonb, TRUE),
  ('RTX', 'RTX Corp', 'equity', 'industrials', '["mega_liquid"]'::jsonb, TRUE),
  ('IBM', 'IBM', 'equity', 'technology', '["mega_liquid"]'::jsonb, TRUE),
  ('AMGN', 'Amgen Inc', 'equity', 'healthcare', '["mega_liquid"]'::jsonb, TRUE),
  ('BLK', 'BlackRock Inc', 'equity', 'financials', '["mega_liquid"]'::jsonb, TRUE),
  ('NOW', 'ServiceNow', 'equity', 'technology', '["mega_liquid"]'::jsonb, TRUE),
  ('BA', 'Boeing Co', 'equity', 'industrials', '["mega_liquid"]'::jsonb, TRUE),
  ('BKNG', 'Booking Holdings', 'equity', 'consumer_discretionary', '["mega_liquid"]'::jsonb, TRUE),
  ('GE', 'General Electric', 'equity', 'industrials', '["mega_liquid"]'::jsonb, TRUE),
  ('SBUX', 'Starbucks Corp', 'equity', 'consumer_discretionary', '["mega_liquid"]'::jsonb, TRUE),
  ('ISRG', 'Intuitive Surgical', 'equity', 'healthcare', '["mega_liquid"]'::jsonb, TRUE),
  ('AMAT', 'Applied Materials', 'equity', 'technology', '["mega_liquid"]'::jsonb, TRUE),
  ('GILD', 'Gilead Sciences', 'equity', 'healthcare', '["mega_liquid"]'::jsonb, TRUE),
  ('DE', 'Deere and Co', 'equity', 'industrials', '["mega_liquid"]'::jsonb, TRUE),
  ('ADP', 'Automatic Data Processing', 'equity', 'industrials', '["mega_liquid"]'::jsonb, TRUE),
  ('LMT', 'Lockheed Martin', 'equity', 'industrials', '["mega_liquid"]'::jsonb, TRUE),
  ('MDLZ', 'Mondelez', 'equity', 'consumer_staples', '["mega_liquid"]'::jsonb, TRUE),
  ('SYK', 'Stryker Corp', 'equity', 'healthcare', '["mega_liquid"]'::jsonb, TRUE),
  ('TJX', 'TJX Companies', 'equity', 'consumer_discretionary', '["mega_liquid"]'::jsonb, TRUE),
  ('PLD', 'Prologis', 'equity', 'real_estate', '["mega_liquid"]'::jsonb, TRUE),
  ('ADI', 'Analog Devices', 'equity', 'technology', '["mega_liquid"]'::jsonb, TRUE),
  ('CB', 'Chubb Ltd', 'equity', 'financials', '["mega_liquid"]'::jsonb, TRUE),
  ('MMC', 'Marsh and McLennan', 'equity', 'financials', '["mega_liquid"]'::jsonb, TRUE),
  ('C', 'Citigroup', 'equity', 'financials', '["mega_liquid"]'::jsonb, TRUE),
  ('SLB', 'Schlumberger', 'equity', 'energy', '["mega_liquid"]'::jsonb, TRUE),
  ('ETN', 'Eaton Corp', 'equity', 'industrials', '["mega_liquid"]'::jsonb, TRUE),
  ('CVS', 'CVS Health', 'equity', 'healthcare', '["mega_liquid"]'::jsonb, TRUE),
  ('PYPL', 'PayPal', 'equity', 'financials', '["mega_liquid"]'::jsonb, TRUE),
  ('MO', 'Altria Group', 'equity', 'consumer_staples', '["mega_liquid"]'::jsonb, TRUE),
  ('USB', 'US Bancorp', 'equity', 'financials', '["mega_liquid"]'::jsonb, TRUE),
  ('PNC', 'PNC Financial', 'equity', 'financials', '["mega_liquid"]'::jsonb, TRUE),
  ('AON', 'Aon plc', 'equity', 'financials', '["mega_liquid"]'::jsonb, TRUE),
  ('APD', 'Air Products', 'equity', 'materials', '["mega_liquid"]'::jsonb, TRUE),
  ('CI', 'Cigna Group', 'equity', 'healthcare', '["mega_liquid"]'::jsonb, TRUE),
  ('GM', 'General Motors', 'equity', 'consumer_discretionary', '["mega_liquid"]'::jsonb, TRUE),
  ('F', 'Ford Motor', 'equity', 'consumer_discretionary', '["mega_liquid"]'::jsonb, TRUE),
  ('COP', 'ConocoPhillips', 'equity', 'energy', '["mega_liquid"]'::jsonb, TRUE),
  ('FDX', 'FedEx Corp', 'equity', 'industrials', '["mega_liquid"]'::jsonb, TRUE),
  ('T', 'AT and T', 'equity', 'communication_services', '["mega_liquid"]'::jsonb, TRUE),
  ('SO', 'Southern Co', 'equity', 'utilities', '["mega_liquid"]'::jsonb, TRUE),
  ('DUK', 'Duke Energy', 'equity', 'utilities', '["mega_liquid"]'::jsonb, TRUE),
  ('EOG', 'EOG Resources', 'equity', 'energy', '["mega_liquid"]'::jsonb, TRUE),
  ('EMR', 'Emerson Electric', 'equity', 'industrials', '["mega_liquid"]'::jsonb, TRUE),
  ('EW', 'Edwards Lifesciences', 'equity', 'healthcare', '["mega_liquid"]'::jsonb, TRUE),
  ('CL', 'Colgate Palmolive', 'equity', 'consumer_staples', '["mega_liquid"]'::jsonb, TRUE),
  ('HCA', 'HCA Healthcare', 'equity', 'healthcare', '["mega_liquid"]'::jsonb, TRUE),
  ('ICE', 'Intercontinental Exchange', 'equity', 'financials', '["mega_liquid"]'::jsonb, TRUE),
  ('ITW', 'Illinois Tool Works', 'equity', 'industrials', '["mega_liquid"]'::jsonb, TRUE),
  ('KMB', 'Kimberly Clark', 'equity', 'consumer_staples', '["mega_liquid"]'::jsonb, TRUE),
  ('MCO', 'Moodys Corp', 'equity', 'financials', '["mega_liquid"]'::jsonb, TRUE),
  ('MMM', '3M Co', 'equity', 'industrials', '["mega_liquid"]'::jsonb, TRUE),
  ('MRNA', 'Moderna', 'equity', 'healthcare', '["mega_liquid"]'::jsonb, TRUE),
  ('MU', 'Micron Technology', 'equity', 'technology', '["mega_liquid"]'::jsonb, TRUE),
  ('PANW', 'Palo Alto Networks', 'equity', 'technology', '["mega_liquid"]'::jsonb, TRUE),
  ('SHW', 'Sherwin Williams', 'equity', 'materials', '["mega_liquid"]'::jsonb, TRUE),
  ('WM', 'Waste Management', 'equity', 'industrials', '["mega_liquid"]'::jsonb, TRUE),
  ('ZTS', 'Zoetis', 'equity', 'healthcare', '["mega_liquid"]'::jsonb, TRUE),
  ('AXP', 'American Express', 'equity', 'financials', '["mega_liquid"]'::jsonb, TRUE),
  ('AME', 'AMETEK', 'equity', 'industrials', '["mega_liquid"]'::jsonb, TRUE),
  ('AIG', 'American International Group', 'equity', 'financials', '["mega_liquid"]'::jsonb, TRUE),
  ('ALL', 'Allstate Corp', 'equity', 'financials', '["mega_liquid"]'::jsonb, TRUE),
  ('ANET', 'Arista Networks', 'equity', 'technology', '["mega_liquid"]'::jsonb, TRUE),
  ('APH', 'Amphenol Corp', 'equity', 'technology', '["mega_liquid"]'::jsonb, TRUE),
  ('AZO', 'AutoZone', 'equity', 'consumer_discretionary', '["mega_liquid"]'::jsonb, TRUE),
  ('BDX', 'Becton Dickinson', 'equity', 'healthcare', '["mega_liquid"]'::jsonb, TRUE),
  ('BSX', 'Boston Scientific', 'equity', 'healthcare', '["mega_liquid"]'::jsonb, TRUE),
  ('CCI', 'Crown Castle', 'equity', 'real_estate', '["mega_liquid"]'::jsonb, TRUE),
  ('CDNS', 'Cadence Design Systems', 'equity', 'technology', '["mega_liquid"]'::jsonb, TRUE),
  ('CEG', 'Constellation Energy', 'equity', 'utilities', '["mega_liquid"]'::jsonb, TRUE),
  ('CHTR', 'Charter Communications', 'equity', 'communication_services', '["mega_liquid"]'::jsonb, TRUE),
  ('CMG', 'Chipotle Mexican Grill', 'equity', 'consumer_discretionary', '["mega_liquid"]'::jsonb, TRUE),
  ('CRWD', 'CrowdStrike', 'equity', 'technology', '["mega_liquid"]'::jsonb, TRUE),
  ('CTAS', 'Cintas Corp', 'equity', 'industrials', '["mega_liquid"]'::jsonb, TRUE),
  ('DD', 'DuPont', 'equity', 'materials', '["mega_liquid"]'::jsonb, TRUE),
  ('DG', 'Dollar General', 'equity', 'consumer_staples', '["mega_liquid"]'::jsonb, TRUE),
  ('DLR', 'Digital Realty', 'equity', 'real_estate', '["mega_liquid"]'::jsonb, TRUE),
  ('EA', 'Electronic Arts', 'equity', 'communication_services', '["mega_liquid"]'::jsonb, TRUE),
  ('EL', 'Estee Lauder', 'equity', 'consumer_staples', '["mega_liquid"]'::jsonb, TRUE),
  ('EXC', 'Exelon Corp', 'equity', 'utilities', '["mega_liquid"]'::jsonb, TRUE),
  ('FIS', 'Fidelity National Info', 'equity', 'financials', '["mega_liquid"]'::jsonb, TRUE),
  ('FISV', 'Fiserv', 'equity', 'financials', '["mega_liquid"]'::jsonb, TRUE),
  ('GD', 'General Dynamics', 'equity', 'industrials', '["mega_liquid"]'::jsonb, TRUE),
  ('GIS', 'General Mills', 'equity', 'consumer_staples', '["mega_liquid"]'::jsonb, TRUE),
  ('HAL', 'Halliburton', 'equity', 'energy', '["mega_liquid"]'::jsonb, TRUE),
  ('HUM', 'Humana', 'equity', 'healthcare', '["mega_liquid"]'::jsonb, TRUE),
  ('INTU', 'Intuit', 'equity', 'technology', '["mega_liquid"]'::jsonb, TRUE),
  ('KHC', 'Kraft Heinz', 'equity', 'consumer_staples', '["mega_liquid"]'::jsonb, TRUE),
  ('KLAC', 'KLA Corp', 'equity', 'technology', '["mega_liquid"]'::jsonb, TRUE),
  ('LRCX', 'Lam Research', 'equity', 'technology', '["mega_liquid"]'::jsonb, TRUE),
  ('MAR', 'Marriott', 'equity', 'consumer_discretionary', '["mega_liquid"]'::jsonb, TRUE),
  ('MET', 'MetLife', 'equity', 'financials', '["mega_liquid"]'::jsonb, TRUE),
  ('MS', 'Morgan Stanley', 'equity', 'financials', '["mega_liquid"]'::jsonb, TRUE),
  ('NEM', 'Newmont Corp', 'equity', 'materials', '["mega_liquid"]'::jsonb, TRUE),
  ('NSC', 'Norfolk Southern', 'equity', 'industrials', '["mega_liquid"]'::jsonb, TRUE),
  ('OXY', 'Occidental Petroleum', 'equity', 'energy', '["mega_liquid"]'::jsonb, TRUE),
  ('PCAR', 'PACCAR', 'equity', 'industrials', '["mega_liquid"]'::jsonb, TRUE),
  ('REGN', 'Regeneron', 'equity', 'healthcare', '["mega_liquid"]'::jsonb, TRUE),
  ('ROST', 'Ross Stores', 'equity', 'consumer_discretionary', '["mega_liquid"]'::jsonb, TRUE),
  ('SNPS', 'Synopsys', 'equity', 'technology', '["mega_liquid"]'::jsonb, TRUE),
  ('TGT', 'Target Corp', 'equity', 'consumer_staples', '["mega_liquid"]'::jsonb, TRUE),
  ('VLO', 'Valero Energy', 'equity', 'energy', '["mega_liquid"]'::jsonb, TRUE),
  ('WBA', 'Walgreens Boots Alliance', 'equity', 'consumer_staples', '["mega_liquid"]'::jsonb, TRUE),
  ('WFC', 'Wells Fargo', 'equity', 'financials', '["mega_liquid"]'::jsonb, TRUE),
  ('WELL', 'Welltower', 'equity', 'real_estate', '["mega_liquid"]'::jsonb, TRUE),
  ('XEL', 'Xcel Energy', 'equity', 'utilities', '["mega_liquid"]'::jsonb, TRUE),
  ('YUM', 'Yum Brands', 'equity', 'consumer_discretionary', '["mega_liquid"]'::jsonb, TRUE),
  ('CSX', 'CSX Corp', 'equity', 'industrials', '["mega_liquid"]'::jsonb, TRUE),
  ('PSX', 'Phillips 66', 'equity', 'energy', '["mega_liquid"]'::jsonb, TRUE),
  ('MPC', 'Marathon Petroleum', 'equity', 'energy', '["mega_liquid"]'::jsonb, TRUE),
  ('DVN', 'Devon Energy', 'equity', 'energy', '["mega_liquid"]'::jsonb, TRUE),
  ('PXD', 'Pioneer Natural Resources', 'equity', 'energy', '["mega_liquid"]'::jsonb, TRUE),
  ('KMI', 'Kinder Morgan', 'equity', 'energy', '["mega_liquid"]'::jsonb, TRUE),
  ('BKR', 'Baker Hughes', 'equity', 'energy', '["mega_liquid"]'::jsonb, TRUE),
  ('MELI', 'MercadoLibre', 'equity', 'consumer_discretionary', '["mega_liquid"]'::jsonb, TRUE),
  ('UBER', 'Uber Technologies', 'equity', 'industrials', '["mega_liquid"]'::jsonb, TRUE),
  ('LYFT', 'Lyft Inc', 'equity', 'industrials', '["mega_liquid"]'::jsonb, TRUE),
  ('SHOP', 'Shopify', 'equity', 'technology', '["mega_liquid"]'::jsonb, TRUE),
  ('SQ', 'Block Inc', 'equity', 'financials', '["mega_liquid"]'::jsonb, TRUE),
  ('COIN', 'Coinbase Global', 'equity', 'financials', '["mega_liquid"]'::jsonb, TRUE),
  ('ROKU', 'Roku Inc', 'equity', 'communication_services', '["mega_liquid"]'::jsonb, TRUE),
  ('SNOW', 'Snowflake', 'equity', 'technology', '["mega_liquid"]'::jsonb, TRUE),
  ('DDOG', 'Datadog', 'equity', 'technology', '["mega_liquid"]'::jsonb, TRUE),
  ('NET', 'Cloudflare', 'equity', 'technology', '["mega_liquid"]'::jsonb, TRUE),
  ('MDB', 'MongoDB', 'equity', 'technology', '["mega_liquid"]'::jsonb, TRUE),
  ('PLTR', 'Palantir', 'equity', 'technology', '["mega_liquid","ai"]'::jsonb, TRUE),
  ('SMCI', 'Super Micro Computer', 'equity', 'technology', '["mega_liquid","ai"]'::jsonb, TRUE),
  ('ARM', 'ARM Holdings', 'equity', 'technology', '["mega_liquid"]'::jsonb, TRUE),
  ('ASML', 'ASML Holding', 'equity', 'technology', '["mega_liquid"]'::jsonb, TRUE),
  ('BABA', 'Alibaba Group', 'equity', 'consumer_discretionary', '["mega_liquid"]'::jsonb, TRUE),
  ('PDD', 'PDD Holdings', 'equity', 'consumer_discretionary', '["mega_liquid"]'::jsonb, TRUE),
  ('NVO', 'Novo Nordisk', 'equity', 'healthcare', '["mega_liquid"]'::jsonb, TRUE),
  ('LLY', 'Eli Lilly', 'equity', 'healthcare', '["mega_liquid"]'::jsonb, TRUE)
ON CONFLICT (symbol) DO UPDATE
SET
  name = EXCLUDED.name,
  asset_type = EXCLUDED.asset_type,
  sector = EXCLUDED.sector,
  tags = EXCLUDED.tags,
  is_active = TRUE;
